// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Money.CompiledModels
{
    public partial class MoneyDbContextModel
    {
        private MoneyDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("7142a662-4181-41c0-bc76-437a47bfe7c0"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var todoItem = TodoItemEntityType.Create(this);

            TodoItemEntityType.CreateAnnotations(todoItem);

            AddAnnotation("ProductVersion", "9.0.9");
        }
    }
}
