// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Money.CompiledModels;
using Money.EntityFrameworkCore;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(MoneyDbContext), typeof(MoneyDbContextModel))]
