// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Money.CompiledModels
{
    public partial class MoneyDbContextModel
    {
        private MoneyDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("03e73819-f2a4-4677-8290-8268b91fa984"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var setting = SettingEntityType.Create(this);

            SettingEntityType.CreateAnnotations(setting);

            AddAnnotation("ProductVersion", "9.0.9");
        }
    }
}
