@Money.HttpApi.Host_HostAddress = https://localhost:5001

GET {{Money.HttpApi.Host_HostAddress}}/api/v1/Settings

###


PUT {{Money.HttpApi.Host_HostAddress}}/api/v1/Settings/base-currency/CAD
Content-Type: application/json
{

}

###
